### ISSUE TITLE
Latest uuid 0.8 is incompatible in some fashion

### ISSUE THREAD

**Issue by nlfiedler** [ivanceras/blob-uuid#3]
Didn't look into it too closely, just tried updating uuid to 0.8 and blob-uuid fails to compile as a result. Something about the `Uuid` struct is different. When I have time, I'll try to investigate.

**Comment by ivanceras** [comment]
Make sure you enable v4 features in uuid

features = ["serde", "v4"]

**Comment by nlfiedler** [comment]
Ah, good point. I tried that, but still same result:

```
error[E0308]: mismatched types
  --> src/core.rs:41:24
   |
41 |     blob_uuid::to_blob(&uuid)
   |                        ^^^^^ expected struct `uuid::Uuid`, found a different struct `uuid::Uuid`
   |
   = note: expected type `&uuid::Uuid` (struct `uuid::Uuid`)
              found type `&uuid::Uuid` (struct `uuid::Uuid`)
note: Perhaps two different versions of crate `uuid` are being used?
  --> src/core.rs:41:24
   |
41 |     blob_uuid::to_blob(&uuid)
   |                        ^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `zorigami`.

To learn more, run the command again with --verbose.
```

Here are the `uuid` lines from my `Cargo.toml`:

```shell
$ grep uuid Cargo.toml
blob-uuid = "0.3.1"
uuid = { version = "0.8", features = ["serde", "v4", "v5"] }
```

Did I get it wrong?

Thanks for your help.

**Comment by ivanceras** [comment]
I think I have to reexport the uuid types used in this crate.
Right now it is using `uuid = { version = "0.7.1", features = ["v4"] }`
You can either use the same version of the uuid I'm using or I can also bump up the uuid version to the latest and publish a new release.

**Comment by nlfiedler** [comment]
I'm fine with using the 0.7 version of uuid. Thanks.

**Comment by ivanceras** [comment]
FYI, I just released a new version of blob-uuid using the latest version of uuid. 
Thanks for filing the issue @nlfiedler .
